package com.create.productionline.client.ponder;

import com.create.productionline.block.SchemeLoaderBlock;
import com.create.productionline.block.entity.SchemeLoaderBlockEntity;
import com.create.productionline.item.LineSchemeItem;
import com.create.productionline.line.scheme.LineScheme;
import com.create.productionline.line.scheme.LineSchemeSerializer;
import com.create.productionline.menu.GuiLayout;
import com.create.productionline.registry.ModBlocks;
import com.create.productionline.registry.ModItems;
import com.simibubi.create.content.kinetics.belt.BeltBlockEntity;
import com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity;

import net.createmod.ponder.api.PonderPalette;
import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.RedstoneLampBlock;
import net.minecraft.world.phys.Vec3;

/**
 * The line story, as the two chapters the author's table describes: the computer writes a plan, the
 * cabinet puts it to work. Both storyboards are registered for both machines by
 * {@link ProductionLinePonderPlugin}, so they are one entry with two chapters and the ponder screen
 * offers A/D to move between them.
 *
 * <p><b>The schematic holds every block; the scene only shows and hides them.</b> That is Create's own
 * arrangement, and here it is not a matter of taste: {@code scene.world().setBlock} goes through
 * Ponder's {@code ReplaceBlocksInstruction}, which starts with
 * {@code if (level.getBounds().isInside(pos))} — and the level's bounds are the bounding box of the
 * blocks the schematic actually <em>placed</em>, not of its declared {@code size}. A scene that places
 * its machine at y=1 on a plate-only schematic (y=0) therefore has that machine silently dropped:
 * the plate appears (it comes from the schematic) and the machine does not, with no error in the log.
 * The schematics under {@code assets/create_productionline/ponder/} carry the machines, the cabinet's
 * lamp, and the belt/Deployer picture for exactly this reason; they are generated by
 * {@code tools/ponder-schematics.js}, which those files' comments explain in full.
 *
 * <p>They are gzip-compressed vanilla structure NBT, and {@code size} plus every block's {@code pos}
 * must be a {@code TAG_List} of {@code TAG_Int}: written as {@code TAG_Int_Array} they load as an empty
 * structure with no error at all, which is what left the scenes blank twice.
 *
 * <p>Text elements are numbered by the order they are shown — {@code text_1}, {@code text_2}, — so
 * the order of {@code showText} calls here is the order of the narration table.
 */
public final class ProductionLineScenes {

    private static final ResourceLocation COMPUTER_GUI = ResourceLocation.fromNamespaceAndPath(
            "create_productionline", "textures/gui/production_computer.png");
    private static final ResourceLocation LOADER_GUI = ResourceLocation.fromNamespaceAndPath(
            "create_productionline", "textures/gui/scheme_loader.png");

    /** The screens' title label y for the panels whose well starts at y=17. */
    private static final int TITLE_Y = 6;

    /** Where the closing picture's belt and Deployers live in the loader schematic. */
    private static final int PREVIEW_ROW_Z = 1;
    /**
     * The Deployers hang two cells above the belt, leaving one empty cell between hand and belt: a
     * Deployer always acts on the position two blocks in front of itself, so one cell higher would make
     * it reach the plate instead of the belt. Kept in step with {@code tools/ponder-schematics.js} and
     * asserted by the self test.
     */
    private static final int DEPLOYER_Y = 3;
    /**
     * Create drives a belt at {@code getSpeed() / 480} blocks per tick, and negates that on the x axis
     * ({@code BeltBlockEntity.getDirectionAwareBeltMovementSpeed}), so an east-facing belt carries items
     * east only at a NEGATIVE speed — which is why Create's own compacting.nbt ships {@code facing:east}
     * with {@code Speed:-32}. The schematic bakes that value and the scene re-states it.
     */
    private static final float BELT_SPEED = -32.0F;
    /** One belt cell per 15 ticks at that speed ({@code 480 / 32}); the travel timings below rely on it. */
    private static final int BELT_TICKS_PER_BLOCK = 15;

    private ProductionLineScenes() {
    }

    /**
     * The position the narration boxes are anchored to. Ponder places a speech box at
     * {@code (min(0.75 * width, projectedX + 50), projectedY + 3)} —it follows the pointed position —     * and this mod's GUI panel sits in the top-right corner. Pointing at the machine's <em>near-bottom</em>
     * corner (the side facing the camera, one pixel above the plate) drops the box to about two thirds of
     * the screen height, clear of the panel, while still marking the machine for the reader. Pointing at
     * {@code topOf(machine)} instead lands the box exactly under the panel — that is the overlap that was
     * seen in game.
     */
    static Vec3 highlight(SceneBuildingUtil util, BlockPos pos) {
        return util.vector().of(pos.getX() + 0.05, pos.getY() + 0.05, pos.getZ() + 0.05);
    }

    // --- chapter 1: the computer writes the plan ---------------------------------

    public static void productionComputer(SceneBuilder builder, SceneBuildingUtil util) {
        com.simibubi.create.foundation.ponder.CreateSceneBuilder scene =
                new com.simibubi.create.foundation.ponder.CreateSceneBuilder(builder);
        scene.title(ProductionLinePonderPlugin.COMPUTER_SCENE, "Writing a Line Scheme");

        BlockPos machine = util.grid().at(2, 1, 2);
        ItemStack target = new ItemStack(Items.IRON_INGOT, 8);
        ItemStack blankScheme = new ItemStack(ModItems.LINE_SCHEME.get());
        ItemStack paper = new ItemStack(Items.PAPER);
        ItemStack writtenScheme = writtenScheme();

        scene.configureBasePlate(0, 0, 5);
        scene.scaleSceneView(0.9F);

        // The base plate is the schematic's layer 0, the machine its only other block: both are
        // revealed from the schematic (see the class comment for why nothing is placed here).
        scene.world().showSection(util.select().layer(0), Direction.UP);
        scene.idle(10);
        scene.world().showSection(util.select().position(machine), Direction.DOWN);
        scene.idle(15);
        scene.special().movePointOfInterest(machine);

        MachineGuiElement panel = new MachineGuiElement(COMPUTER_GUI,
                new int[]{GuiLayout.computerSlotX(0), GuiLayout.computerSlotX(1), GuiLayout.computerSlotX(2)},
                new int[]{GuiLayout.COMPUTER_SLOT_Y, GuiLayout.COMPUTER_SLOT_Y, GuiLayout.COMPUTER_SLOT_Y},
                ModBlocks.PRODUCTION_COMPUTER.get().getName(), TITLE_Y, false)
                .withButton((GuiLayout.PANEL_WIDTH - GuiLayout.COMPUTER_BUTTON_WIDTH) / 2,
                        GuiLayout.COMPUTER_BUTTON_Y, GuiLayout.COMPUTER_BUTTON_WIDTH,
                        GuiLayout.COMPUTER_BUTTON_HEIGHT,
                        Component.translatable("gui.create_productionline.compute"));
        scene.addInstruction(s -> s.addElement(panel));

        // 1 —what the machine is for
        scene.addInstruction(s -> panel.setVisible(true));
        scene.overlay().showText(70)
                .attachKeyFrame()
                .text("Turn any recipe into a production line plan")
                .colored(PonderPalette.GREEN)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(80);

        // 2 —what goes into the first two slots
        scene.addInstruction(s -> panel.setStack(0, target));
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("Slot 1 takes the item to produce, slot 2 a blank Line Scheme")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(60);
        scene.addInstruction(s -> panel.setStack(1, blankScheme));
        scene.idle(60);

        // 3 —the optional paper carrier
        scene.addInstruction(s -> panel.setStack(2, paper));
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("Slot 3 may hold paper: it stays readable as a manual after the scheme is loaded")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 4 — press Compute. The cue is the button in the panel, not a click on the block: the block only
        // opens the GUI, while the action the narration describes is pressing 【计算】.
        scene.addInstruction(s -> panel.setButtonHighlighted(true));
        scene.overlay().showText(70)
                .attachKeyFrame()
                .text("Press Compute: the server derives it from its live recipes and writes the scheme")
                .colored(PonderPalette.INPUT)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.effects().indicateSuccess(machine);
        scene.addInstruction(s -> panel.setStack(1, writtenScheme));
        scene.idle(45);
        scene.addInstruction(s -> panel.setButtonHighlighted(false));
        scene.idle(35);

        // 5 —what the written scheme says
        scene.overlay().showText(90)
                .attachKeyFrame()
                .text("The scheme names the product, the base and the whole chain; a self-referencing "
                        + "recipe is marked as an incremental line")
                .colored(PonderPalette.OUTPUT)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(100);
        scene.markAsFinished();
    }

    // --- chapter 2: the cabinet loads it -----------------------------------------

    public static void schemeLoader(SceneBuilder builder, SceneBuildingUtil util) {
        com.simibubi.create.foundation.ponder.CreateSceneBuilder scene =
                new com.simibubi.create.foundation.ponder.CreateSceneBuilder(builder);
        scene.title(ProductionLinePonderPlugin.LOADER_SCENE, "Loading the scheme");

        BlockPos machine = util.grid().at(2, 1, 2);
        BlockPos lamp = util.grid().at(2, 2, 2);
        ItemStack writtenScheme = writtenScheme();

        int[] loaderSlotsX = new int[16];
        int[] loaderSlotsY = new int[16];
        for (int i = 0; i < 16; i++) {
            loaderSlotsX[i] = GuiLayout.loaderSlotX(i % 8);
            loaderSlotsY[i] = GuiLayout.loaderSlotY(i / 8);
        }

        scene.configureBasePlate(0, 0, 5);
        scene.scaleSceneView(0.9F);

        // Everything this chapter shows —the cabinet, the lamp that lights up, the belt and the two
        // Deployers of the closing picture —is in the schematic; the scene reveals it step by step.
        scene.world().showSection(util.select().layer(0), Direction.UP);
        scene.idle(10);
        scene.world().showSection(util.select().position(machine), Direction.DOWN);
        scene.idle(15);
        scene.special().movePointOfInterest(machine);

        MachineGuiElement panel = new MachineGuiElement(LOADER_GUI, loaderSlotsX, loaderSlotsY,
                ModBlocks.SCHEME_LOADER.get().getName(), GuiLayout.LOADER_TITLE_Y, false);
        scene.addInstruction(s -> s.addElement(panel));

        // 1 —the scheme goes in
        scene.addInstruction(s -> panel.setVisible(true));
        scene.addInstruction(s -> panel.setStack(0, writtenScheme));
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("Put the written scheme into any slot of a Scheme Loader")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 2 —it takes effect at once, and the bar lights up
        scene.world().modifyBlock(machine, state -> state.setValue(SchemeLoaderBlock.FILL, 1), false);
        scene.effects().indicateSuccess(machine);
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("It takes effect immediately: only the recipes refresh, the server does not reload")
                .colored(PonderPalette.GREEN)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 3 —more schemes, more of the bar
        scene.addInstruction(s -> {
            panel.setStack(1, writtenScheme.copy());
            panel.setStack(2, writtenScheme.copy());
        });
        scene.world().modifyBlock(machine, state -> state.setValue(SchemeLoaderBlock.FILL, 3), false);
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("The bar on its side shows how much of the cabinet is in use")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 4 — redstone while recipes are active: the lamp sits directly on the cabinet, so the picture shows
        // the machine driving it. The cabinet really is a source (SchemeLoaderBlock#getSignal reports 15
        // while its block entity is active), and the lamp is switched on here. A vanilla wire between them
        // was tried twice — baked at 15, then powered from here — and rendered dark both times, so it is not
        // part of the picture: its brightness never followed the value written to it in a ponder world.
        scene.world().showSection(util.select().position(lamp), Direction.UP);
        scene.world().modifyBlockEntityNBT(util.select().position(machine), SchemeLoaderBlockEntity.class,
                nbt -> nbt.putBoolean("Active", true));
        scene.idle(5);
        scene.world().modifyBlock(lamp, state -> state.setValue(RedstoneLampBlock.LIT, true), false);
        scene.overlay().showText(70)
                .attachKeyFrame()
                .text("While recipes are active the cabinet emits a redstone signal")
                .colored(PonderPalette.RED)
                .placeNearTarget()
                .pointAt(highlight(util, lamp));
        scene.idle(80);
        scene.addInstruction(s -> panel.setVisible(false));

        // 5 — the line the plan describes. The narration comes up first and stays for the whole run, so
        // the reader is told what they are about to watch before anything starts moving.
        scene.world().hideSection(util.select().position(lamp), Direction.UP);
        scene.world().hideSection(util.select().position(machine), Direction.UP);
        scene.idle(10);
        scene.overlay().showText(210)
                .attachKeyFrame()
                .text("Build the line the scheme describes as a sequenced assembly, and keep it supplied")
                .placeNearTarget()
                .pointAt(highlight(util, util.grid().at(2, 1, PREVIEW_ROW_Z)));
        scene.idle(10);
        buildLinePreview(scene, util);
        scene.idle(30);
        scene.markAsFinished();
    }

    /**
     * The closing picture, and it is a working line rather than a diagram of one.
     *
     * <p><b>Powered.</b> The schematic carries a Creative Motor beside the belt's first pulley, and the
     * scene sets the speed on exactly those cells — {@code setKineticSpeed} writes the speed onto the
     * kinetic block entities of a selection, which is how Create's own scenes start a belt
     * ({@code DeployerScenes} does {@code setKineticSpeed(select().layer(1), -32F)}).
     *
     * <p><b>Built like a real one.</b> Five belt cells, with the two Deployers on the second and the
     * fourth, hanging two cells above the belt: a Deployer acts on the position two blocks in front of
     * itself, so the empty cell in between is what puts its hand on the belt. The first one is shown
     * holding the material it adds, so the picture says what the narration says.
     *
     * <p><b>Running the whole process.</b> The raw iron is fed in at the belt's first cell, the line
     * carries it to the first Deployer (which turns it into a Generic Intermediate — this mod's own item,
     * exactly what an unfinished line item is), on to the second (which finishes it into the product), and
     * off the end of the belt. The item is driven by rewriting the belt's own {@code Inventory} NBT rather
     * than by {@code createItemOnBelt}, which never produced a visible item here; the travel timings come
     * from the belt speed itself ({@link #BELT_TICKS_PER_BLOCK}).
     */
    private static void buildLinePreview(com.simibubi.create.foundation.ponder.CreateSceneBuilder scene,
            SceneBuildingUtil util) {
        // The power train and the belt it drives: motor at (0, 1, 0), belt along z = PREVIEW_ROW_Z.
        BlockPos first = util.grid().at(1, DEPLOYER_Y, PREVIEW_ROW_Z);
        BlockPos second = util.grid().at(3, DEPLOYER_Y, PREVIEW_ROW_Z);
        var line = util.select().position(0, 1, PREVIEW_ROW_Z - 1)
                .add(util.select().fromTo(0, 1, PREVIEW_ROW_Z, 4, 1, PREVIEW_ROW_Z));
        var deployers = util.select().position(first).add(util.select().position(second));

        scene.world().showSection(line, Direction.DOWN);
        scene.idle(5);
        scene.world().setKineticSpeed(line, BELT_SPEED);
        scene.idle(5);

        scene.world().showSection(deployers, Direction.UP);
        scene.world().setKineticSpeed(deployers, BELT_SPEED);
        // The first Deployer holds the material it adds, so the picture says what the narration says.
        scene.world().modifyBlockEntityNBT(util.select().position(first), DeployerBlockEntity.class,
                nbt -> nbt.put("HeldItem",
                        new ItemStack(Items.COAL).saveOptional(scene.world().getHolderLookupProvider())));
        scene.idle(10);

        // Raw iron in at the belt's input. The item stays locked from here to the last station and this
        // scene writes its position in small steps (carryItem): letting the belt move it as well made the
        // two motions fight, which read as the item twitching on the belt.
        ItemStack rawIron = new ItemStack(Items.RAW_IRON);
        setBeltItem(scene, util, rawIron, 0.5F, true);
        scene.idle(8);

        carryItem(scene, util, rawIron, 0.5F, 1.5F);

        // Station 1: the first Deployer works on it and it comes out an unfinished intermediate.
        scene.world().moveDeployer(first, 1f, 12);
        scene.idle(12);
        setBeltItem(scene, util, new ItemStack(ModItems.GENERIC_INTERMEDIATE.get()), 1.5F, true);
        scene.effects().indicateSuccess(first);
        scene.world().moveDeployer(first, -1f, 12);
        scene.idle(14);

        carryItem(scene, util, new ItemStack(ModItems.GENERIC_INTERMEDIATE.get()), 1.5F, 3.5F);

        // Station 2: the second Deployer finishes it into the product.
        scene.world().moveDeployer(second, 1f, 12);
        scene.idle(12);
        setBeltItem(scene, util, new ItemStack(Items.IRON_INGOT), 3.5F, true);
        scene.effects().indicateSuccess(second);
        scene.world().moveDeployer(second, -1f, 12);
        scene.idle(14);

        // Then it is handed back to the belt, which carries it off the end and drops it by itself — one
        // product, ejected by the belt rather than by an entity this scene spawns on top of it.
        carryItem(scene, util, new ItemStack(Items.IRON_INGOT), 3.5F, 4.7F);
        setBeltItem(scene, util, new ItemStack(Items.IRON_INGOT), 4.7F, false);
        scene.idle(25);
    }

    /**
     * Slides the item the given distance along the belt, one tick per step over the ticks the belt itself
     * would need ({@link #BELT_TICKS_PER_BLOCK}), so it reads as the belt carrying it. Every step also
     * records where the item was on the previous tick: the belt's renderer interpolates between the two
     * ({@code lerp(partialTicks, prevBeltPosition, beltPosition)}), and writing both to the same value — as
     * an earlier round did — leaves it nothing to interpolate, which is what made the item move in jumps.
     * The item stays locked throughout; letting the belt move it as well means the two disagree from tick
     * to tick, which read as twitching.
     */
    private static void carryItem(com.simibubi.create.foundation.ponder.CreateSceneBuilder scene,
            SceneBuildingUtil util, ItemStack stack, float from, float to) {
        int steps = Math.max(1, Math.round(Math.abs(to - from) * BELT_TICKS_PER_BLOCK));
        for (int i = 1; i <= steps; i++) {
            float prev = from + (to - from) * (i - 1) / steps;
            float next = from + (to - from) * i / steps;
            setBeltItem(scene, util, stack, next, prev, true);
            scene.idle(1);
        }
    }

    /**
     * Puts one item on the belt, moves it along, or takes it off, by rewriting the belt controller's
     * {@code Inventory} NBT — the shape {@code BeltInventory.write} / {@code TransportedItemStack.serializeNBT}
     * use. This is the route that works here: {@code createItemOnBelt} inserted "successfully" and no item
     * ever appeared. {@code PonderSceneBuilder.modifyBlockEntityNBT} saves the block entity, applies the
     * consumer and reloads it, and the redraw flag makes the belt render the change straight away.
     *
     * <p>{@code pos} is the position along the belt in cells (a cell's centre is its index plus a half),
     * {@code prevPos} the position on the previous tick (the renderer interpolates between them), and
     * {@code locked} holds the item where it is — the state Create itself uses for an item a Deployer is
     * working on.
     */
    private static void setBeltItem(com.simibubi.create.foundation.ponder.CreateSceneBuilder scene,
            SceneBuildingUtil util, ItemStack stack, float pos, boolean locked) {
        setBeltItem(scene, util, stack, pos, pos, locked);
    }

    private static void setBeltItem(com.simibubi.create.foundation.ponder.CreateSceneBuilder scene,
            SceneBuildingUtil util, ItemStack stack, float pos, float prevPos, boolean locked) {
        CompoundTag inventory = beltInventory(scene, stack, pos, prevPos, locked);
        scene.world().modifyBlockEntityNBT(util.select().position(0, 1, PREVIEW_ROW_Z), BeltBlockEntity.class,
                nbt -> nbt.put("Inventory", inventory.copy()), true);
    }

    private static CompoundTag beltInventory(com.simibubi.create.foundation.ponder.CreateSceneBuilder scene,
            ItemStack stack, float pos, float prevPos, boolean locked) {
        CompoundTag inventory = new CompoundTag();
        ListTag items = new ListTag();
        if (!stack.isEmpty()) {
            CompoundTag item = new CompoundTag();
            item.put("Item", stack.saveOptional(scene.world().getHolderLookupProvider()));
            item.putFloat("Pos", pos);
            item.putFloat("PrevPos", prevPos);
            item.putFloat("Offset", 0.0F);
            item.putFloat("PrevOffset", 0.0F);
            item.putInt("InSegment", (int) pos);
            item.putInt("Angle", 0);
            item.putInt("InDirection", Direction.WEST.get3DDataValue());
            item.putBoolean("Locked", locked);
            items.add(item);
        }
        inventory.put("Items", items);
        inventory.putBoolean("PositiveOrder", true);
        return inventory;
    }
    /** A written scheme, built the way the computer builds one —so its steps and tooltip are real. */
    static ItemStack writtenScheme() {
        ItemStack stack = new ItemStack(ModItems.LINE_SCHEME.get());
        LineScheme scheme = new LineScheme();
        scheme.setRecipeId("minecraft:iron_ingot_from_blasting_raw_iron");
        scheme.setOutputItem("minecraft:iron_ingot");
        scheme.setBaseMaterial("minecraft:raw_iron");
        LineScheme.Step feed = scheme.addStep("cpl:feed", 1);
        feed.addInput("minecraft:raw_iron");
        LineScheme.Step deploy = scheme.addStep("create:deploying", 1);
        deploy.addInput("minecraft:coal");
        deploy.addOutput("minecraft:iron_ingot");
        LineSchemeSerializer.saveToStack(stack, scheme);
        return stack;
    }
}
