package com.create.productionline.client.ponder;

import com.create.productionline.block.SchemeLoaderBlock;
import com.create.productionline.item.LineSchemeItem;
import com.create.productionline.line.scheme.LineScheme;
import com.create.productionline.line.scheme.LineSchemeSerializer;
import com.create.productionline.menu.GuiLayout;
import com.create.productionline.registry.ModBlocks;
import com.create.productionline.registry.ModItems;
import com.simibubi.create.content.kinetics.deployer.DeployerBlockEntity;
import com.simibubi.create.foundation.ponder.element.BeltItemElement;

import net.createmod.catnip.math.Pointing;
import net.createmod.ponder.api.PonderPalette;
import net.createmod.ponder.api.element.ElementLink;
import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.RedStoneWireBlock;
import net.minecraft.world.level.block.RedstoneLampBlock;
import net.minecraft.world.phys.Vec3;

/**
 * The line story, as the two chapters the author's table describes: the computer writes a plan, the
 * cabinet puts it to work. Both storyboards are registered for both machines by
 * {@link ProductionLinePonderPlugin}, so they are one entry with two chapters and the ponder screen
 * offers A/D to move between them.
 *
 * <p><b>The schematic holds every block; the scene only shows and hides them.</b> That is Create's own
 * arrangement, and here it is not a matter of taste: {@code scene.world().setBlock} goes through
 * Ponder's {@code ReplaceBlocksInstruction}, which starts with
 * {@code if (level.getBounds().isInside(pos))} — and the level's bounds are the bounding box of the
 * blocks the schematic actually <em>placed</em>, not of its declared {@code size}. A scene that places
 * its machine at y=1 on a plate-only schematic (y=0) therefore has that machine silently dropped:
 * the plate appears (it comes from the schematic) and the machine does not, with no error in the log.
 * The schematics under {@code assets/create_productionline/ponder/} carry the machines, the cabinet's
 * lamp, and the belt/Deployer picture for exactly this reason; they are generated by
 * {@code tools/ponder-schematics.js}, which those files' comments explain in full.
 *
 * <p>They are gzip-compressed vanilla structure NBT, and {@code size} plus every block's {@code pos}
 * must be a {@code TAG_List} of {@code TAG_Int}: written as {@code TAG_Int_Array} they load as an empty
 * structure with no error at all, which is what left the scenes blank twice.
 *
 * <p>Text elements are numbered by the order they are shown — {@code text_1}, {@code text_2}, … — so
 * the order of {@code showText} calls here is the order of the narration table.
 */
public final class ProductionLineScenes {

    private static final ResourceLocation COMPUTER_GUI = ResourceLocation.fromNamespaceAndPath(
            "create_productionline", "textures/gui/production_computer.png");
    private static final ResourceLocation LOADER_GUI = ResourceLocation.fromNamespaceAndPath(
            "create_productionline", "textures/gui/scheme_loader.png");

    /** The screens' title label y for the panels whose well starts at y=17. */
    private static final int TITLE_Y = 6;

    /** Where the closing picture's belt and Deployers live in the loader schematic. */
    private static final int PREVIEW_ROW_Z = 1;
    /**
     * The Deployers hang two cells above the belt, leaving one empty cell between hand and belt: a
     * Deployer always acts on the position two blocks in front of itself, so one cell higher would make
     * it reach the plate instead of the belt. Kept in step with {@code tools/ponder-schematics.js} and
     * asserted by the self test.
     */
    private static final int DEPLOYER_Y = 3;

    private ProductionLineScenes() {
    }

    /**
     * The position the narration boxes are anchored to. Ponder places a speech box at
     * {@code (min(0.75 * width, projectedX + 50), projectedY + 3)} — it follows the pointed position —
     * and this mod's GUI panel sits in the top-right corner. Pointing at the machine's <em>near-bottom</em>
     * corner (the side facing the camera, one pixel above the plate) drops the box to about two thirds of
     * the screen height, clear of the panel, while still marking the machine for the reader. Pointing at
     * {@code topOf(machine)} instead lands the box exactly under the panel — that is the overlap that was
     * seen in game.
     */
    static Vec3 highlight(SceneBuildingUtil util, BlockPos pos) {
        return util.vector().of(pos.getX() + 0.05, pos.getY() + 0.05, pos.getZ() + 0.05);
    }

    // --- chapter 1: the computer writes the plan ---------------------------------

    public static void productionComputer(SceneBuilder builder, SceneBuildingUtil util) {
        com.simibubi.create.foundation.ponder.CreateSceneBuilder scene =
                new com.simibubi.create.foundation.ponder.CreateSceneBuilder(builder);
        scene.title(ProductionLinePonderPlugin.COMPUTER_SCENE, "Writing a Line Scheme");

        BlockPos machine = util.grid().at(2, 1, 2);
        ItemStack target = new ItemStack(Items.IRON_INGOT, 8);
        ItemStack blankScheme = new ItemStack(ModItems.LINE_SCHEME.get());
        ItemStack paper = new ItemStack(Items.PAPER);
        ItemStack writtenScheme = writtenScheme();

        scene.configureBasePlate(0, 0, 5);
        scene.scaleSceneView(0.9F);

        // The base plate is the schematic's layer 0, the machine its only other block: both are
        // revealed from the schematic (see the class comment for why nothing is placed here).
        scene.world().showSection(util.select().layer(0), Direction.UP);
        scene.idle(10);
        scene.world().showSection(util.select().position(machine), Direction.DOWN);
        scene.idle(15);
        scene.special().movePointOfInterest(machine);

        MachineGuiElement panel = new MachineGuiElement(COMPUTER_GUI,
                new int[]{GuiLayout.computerSlotX(0), GuiLayout.computerSlotX(1), GuiLayout.computerSlotX(2)},
                new int[]{GuiLayout.COMPUTER_SLOT_Y, GuiLayout.COMPUTER_SLOT_Y, GuiLayout.COMPUTER_SLOT_Y},
                ModBlocks.PRODUCTION_COMPUTER.get().getName(), TITLE_Y, false)
                .withButton((GuiLayout.PANEL_WIDTH - GuiLayout.COMPUTER_BUTTON_WIDTH) / 2,
                        GuiLayout.COMPUTER_BUTTON_Y, GuiLayout.COMPUTER_BUTTON_WIDTH,
                        GuiLayout.COMPUTER_BUTTON_HEIGHT,
                        Component.translatable("gui.create_productionline.compute"));
        scene.addInstruction(s -> s.addElement(panel));

        // 1 — what the machine is for
        scene.addInstruction(s -> panel.setVisible(true));
        scene.overlay().showText(70)
                .attachKeyFrame()
                .text("Turn any recipe into a production line plan")
                .colored(PonderPalette.GREEN)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(80);

        // 2 — what goes into the first two slots
        scene.addInstruction(s -> panel.setStack(0, target));
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("Slot 1 takes the item to produce, slot 2 a blank Line Scheme")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(60);
        scene.addInstruction(s -> panel.setStack(1, blankScheme));
        scene.idle(60);

        // 3 — the optional paper carrier
        scene.addInstruction(s -> panel.setStack(2, paper));
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("Slot 3 may hold paper: it stays readable as a manual after the scheme is loaded")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 4 — press Compute
        scene.overlay().showControls(util.vector().topOf(machine), Pointing.DOWN, 60).leftClick();
        scene.overlay().showText(70)
                .attachKeyFrame()
                .text("Press Compute: the server derives it from its live recipes and writes the scheme")
                .colored(PonderPalette.INPUT)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.effects().indicateSuccess(machine);
        scene.addInstruction(s -> panel.setStack(1, writtenScheme));
        scene.idle(80);

        // 5 — what the written scheme says
        scene.overlay().showText(90)
                .attachKeyFrame()
                .text("The scheme names the product, the base and the whole chain; a self-referencing "
                        + "recipe is marked as an incremental line")
                .colored(PonderPalette.OUTPUT)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(100);
        scene.markAsFinished();
    }

    // --- chapter 2: the cabinet loads it -----------------------------------------

    public static void schemeLoader(SceneBuilder builder, SceneBuildingUtil util) {
        com.simibubi.create.foundation.ponder.CreateSceneBuilder scene =
                new com.simibubi.create.foundation.ponder.CreateSceneBuilder(builder);
        scene.title(ProductionLinePonderPlugin.LOADER_SCENE, "Loading the scheme");

        BlockPos machine = util.grid().at(2, 1, 2);
        BlockPos lamp = util.grid().at(4, 1, 2);
        BlockPos dust = util.grid().at(3, 1, 2);
        ItemStack writtenScheme = writtenScheme();

        int[] loaderSlotsX = new int[16];
        int[] loaderSlotsY = new int[16];
        for (int i = 0; i < 16; i++) {
            loaderSlotsX[i] = GuiLayout.loaderSlotX(i % 8);
            loaderSlotsY[i] = GuiLayout.loaderSlotY(i / 8);
        }

        scene.configureBasePlate(0, 0, 5);
        scene.scaleSceneView(0.9F);

        // Everything this chapter shows — the cabinet, the lamp that lights up, the belt and the two
        // Deployers of the closing picture — is in the schematic; the scene reveals it step by step.
        scene.world().showSection(util.select().layer(0), Direction.UP);
        scene.idle(10);
        scene.world().showSection(util.select().position(machine), Direction.DOWN);
        scene.idle(15);
        scene.special().movePointOfInterest(machine);

        MachineGuiElement panel = new MachineGuiElement(LOADER_GUI, loaderSlotsX, loaderSlotsY,
                ModBlocks.SCHEME_LOADER.get().getName(), GuiLayout.LOADER_TITLE_Y, false);
        scene.addInstruction(s -> s.addElement(panel));

        // 1 — the scheme goes in
        scene.addInstruction(s -> panel.setVisible(true));
        scene.addInstruction(s -> panel.setStack(0, writtenScheme));
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("Put the written scheme into any slot of a Scheme Loader")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 2 — it takes effect at once, and the bar lights up
        scene.world().modifyBlock(machine, state -> state.setValue(SchemeLoaderBlock.FILL, 1), false);
        scene.effects().indicateSuccess(machine);
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("It takes effect immediately: only the recipes refresh, the server does not reload")
                .colored(PonderPalette.GREEN)
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 3 — more schemes, more of the bar
        scene.addInstruction(s -> {
            panel.setStack(1, writtenScheme.copy());
            panel.setStack(2, writtenScheme.copy());
        });
        scene.world().modifyBlock(machine, state -> state.setValue(SchemeLoaderBlock.FILL, 3), false);
        scene.overlay().showText(80)
                .attachKeyFrame()
                .text("The bar on its side shows how much of the cabinet is in use")
                .placeNearTarget()
                .pointAt(highlight(util, machine));
        scene.idle(90);

        // 4 — redstone while recipes are active: the dust lights up and the lamp comes on with it
        scene.world().showSection(util.select().position(dust), Direction.UP);
        scene.world().showSection(util.select().position(lamp), Direction.EAST);
        scene.idle(5);
        scene.world().modifyBlock(dust, state -> state.setValue(RedStoneWireBlock.POWER, 15), false);
        scene.world().modifyBlock(lamp, state -> state.setValue(RedstoneLampBlock.LIT, true), false);
        scene.overlay().showText(70)
                .attachKeyFrame()
                .text("While recipes are active the cabinet emits a redstone signal")
                .colored(PonderPalette.RED)
                .placeNearTarget()
                .pointAt(highlight(util, dust));
        scene.idle(80);
        scene.addInstruction(s -> panel.setVisible(false));

        // 5 — the line the plan describes
        scene.world().hideSection(util.select().position(lamp), Direction.UP);
        scene.world().hideSection(util.select().position(machine), Direction.UP);
        scene.idle(10);
        buildLinePreview(scene, util);
        scene.overlay().showText(190)
                .attachKeyFrame()
                .text("Build the line it describes: base onto the belt first, one Deployer per added "
                        + "material facing down")
                .placeNearTarget()
                .pointAt(highlight(util, util.grid().at(2, 1, PREVIEW_ROW_Z)));
        scene.idle(200);
        scene.markAsFinished();
    }

    /**
     * The closing picture, and it is a working line rather than a diagram of one.
     *
     * <p><b>Powered.</b> The schematic carries a Creative Motor beside the belt's first pulley, and the
     * scene sets the speed on exactly those cells — {@code setKineticSpeed} writes the speed onto the
     * kinetic block entities of a selection, which is how Create's own scenes start a belt
     * ({@code DeployerScenes} does {@code setKineticSpeed(select().layer(1), -32F)}).
     *
     * <p><b>Spaced like a real one.</b> Both Deployers hang two cells above the belt: a Deployer acts on
     * the position two blocks in front of itself, so the empty cell in between is what puts its hand on
     * the belt. They are also shown holding the material they add, so the picture says what the narration
     * says — one Deployer per added material.
     *
     * <p><b>Carrying the whole story.</b> The base item goes onto the belt, the first Deployer turns it
     * into a Generic Intermediate (this mod's own item, which is exactly what an unfinished line item is),
     * and the second finishes it into the product: base, intermediate and product all travel the belt.
     * The item is stalled under each Deployer while it works, as Create's scenes do, so the two stay in
     * step no matter what speed the line runs at.
     */
    private static void buildLinePreview(com.simibubi.create.foundation.ponder.CreateSceneBuilder scene,
            SceneBuildingUtil util) {
        // The power train and the belt it drives: motor at (0, 1, 0), belt along z = PREVIEW_ROW_Z.
        BlockPos first = util.grid().at(0, DEPLOYER_Y, PREVIEW_ROW_Z);
        BlockPos second = util.grid().at(4, DEPLOYER_Y, PREVIEW_ROW_Z);
        var line = util.select().position(0, 1, PREVIEW_ROW_Z - 1)
                .add(util.select().fromTo(0, 1, PREVIEW_ROW_Z, 4, 1, PREVIEW_ROW_Z));
        var deployers = util.select().fromTo(0, DEPLOYER_Y, PREVIEW_ROW_Z, 4, DEPLOYER_Y, PREVIEW_ROW_Z);

        scene.world().showSection(line, Direction.DOWN);
        scene.idle(5);
        scene.world().setKineticSpeed(line, 32.0F);
        scene.idle(5);

        scene.world().showSection(deployers, Direction.UP);
        scene.world().setKineticSpeed(deployers, -32.0F);
        // The first Deployer holds the material it adds, so the picture says what the narration says.
        scene.world().modifyBlockEntityNBT(util.select().position(first), DeployerBlockEntity.class,
                nbt -> nbt.put("HeldItem",
                        new ItemStack(Items.COAL).saveOptional(scene.world().getHolderLookupProvider())));
        scene.idle(10);

        // The base goes on at the belt's input cell, which is also where the first Deployer waits — so the
        // two are in position from the first tick. Create's own scenes insert at the belt's `start` cell
        // and pass the side the item comes from (a belt facing east takes items from the west).
        ElementLink<BeltItemElement> item = scene.world().createItemOnBelt(
                util.grid().at(0, 1, PREVIEW_ROW_Z), Direction.WEST, new ItemStack(Items.IRON_ORE));
        scene.world().stallBeltItem(item, true);
        scene.idle(10);
        scene.world().moveDeployer(first, 1f, 20);
        scene.idle(20);
        scene.world().changeBeltItemTo(item, new ItemStack(ModItems.GENERIC_INTERMEDIATE.get()));
        scene.effects().indicateSuccess(first);
        scene.world().moveDeployer(first, -1f, 20);
        scene.idle(20);
        scene.world().stallBeltItem(item, false);

        // Let it travel to the end of the belt, where the second Deployer is waiting and where an item
        // stops on its own, so arriving early or late cannot put the two out of step.
        scene.idle(70);
        scene.world().stallBeltItem(item, true);
        scene.world().moveDeployer(second, 1f, 20);
        scene.idle(20);
        scene.world().changeBeltItemTo(item, new ItemStack(Items.IRON_INGOT));
        scene.effects().indicateSuccess(second);
        scene.world().moveDeployer(second, -1f, 20);
        scene.idle(20);
        scene.world().stallBeltItem(item, false);
        scene.idle(15);
    }

    /** A written scheme, built the way the computer builds one — so its steps and tooltip are real. */
    static ItemStack writtenScheme() {
        ItemStack stack = new ItemStack(ModItems.LINE_SCHEME.get());
        LineScheme scheme = new LineScheme();
        scheme.setRecipeId("minecraft:iron_ingot_from_blasting_iron_ore");
        scheme.setOutputItem("minecraft:iron_ingot");
        scheme.setBaseMaterial("minecraft:iron_ore");
        LineScheme.Step feed = scheme.addStep("cpl:feed", 1);
        feed.addInput("minecraft:iron_ore");
        LineScheme.Step deploy = scheme.addStep("create:deploying", 1);
        deploy.addInput("minecraft:coal");
        deploy.addOutput("minecraft:iron_ingot");
        LineSchemeSerializer.saveToStack(stack, scheme);
        return stack;
    }
}
